repo: '#{repo}'
reports: '#{reports}'

league:
  names: 'league-names.dat'

security.jwt:
  tokenExpirationTime: 10080 # 7 days in minutes
  refreshTokenExpTime: 43200 # 30 days
  tokenIssuer: http://rsfa.org
  tokenSigningKey: RnMG9H9bVXW/jrB7aZcYjuZT86gVwn9TRjvkEpR0RPo=