#!/bin/bash

IP="74.110.137.121"
PORT="8080"
LEAGUE=$1
TIER=$2
SEASON=$3
ROUND=$4

URL="http://${IP}:${PORT}"
API="${URL}/api"

curl -X GET \
"${API}/leagues/${LEAGUE}/${TIER}/${SEASON}/rounds/${ROUND}"
