#!/bin/bash

PORT="8080"
IP=$(get-ip)
JWT=$(get-jwt)

LEAGUE=$1
TIER=$2
SEASON=$3
HOME=$4
AWAY=$5

URL="http://${IP}:${PORT}"
API="${URL}/api"

curl -s -X GET \
-H "Authorization: Bearer ${JWT}" \
"${API}/leagues/${LEAGUE}/${TIER}/${SEASON}/results/${HOME}/vs/${AWAY}"
