#!/bin/bash

PORT="8080"
IP=$(get-ip)
JWT=$(get-jwt)

LEAGUE=$1
TIER=$2
SEASON=$3

URL="http://${IP}:${PORT}"
API="${URL}/api"

curl -X GET \
-H "Authorization: Bearer ${JWT}" \
"${API}/leagues/${LEAGUE}/${TIER}/${SEASON}/rounds"
