#!/bin/bash

PORT="8080"
IP=$(get-ip)
JWT=$(get-jwt)

LEAGUE=$1
TIER=$2
SEASON=$3
FROM=$4
TO=$5

URL="http://${IP}:${PORT}"
API="${URL}/api"

curl -s -X GET \
-H "Authorization: Bearer ${JWT}" \
"${API}/leagues/${LEAGUE}/${TIER}/${SEASON}/stats/from/${FROM}/to/${TO}"
